### PR TITLE
Fix archive metadata parsing with missing microseconds

### PR DESCRIPTION
**Pull request by camh-**
datetime.datetime.isoformat() elides microseconds from its string output if the microseconds are zero. The parsing in archive.Archive.ts() needs to be able to handle this.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
looks good, thanks for finding and fixing this!

if you like, you could extract the common code in the test functions into a separate function and call that from the 2 test functions with the not-common stuff as arguments. less duplication.

**Comment by camh-** [comment]
Good idea. Refactored into a common test function.

**Comment by ThomasWaldmann** [comment]
If you're finished, don't forget to push, so the PR gets updated.

**Comment by camh-** [comment]
I believe I have pushed. I see the update commit on this PR. I folded the change into the first commit.

**Comment by ThomasWaldmann** [comment]
ah, ok, github still showed the old "5/7 days ago" timestamps...

**Comment by camh-** [comment]
I expected git rebase to update the commit timestamp of the commit I folded the change into. But I've never paid much attention to the timestamps on rebase. I can update it if it is important.

**Comment by ThomasWaldmann** [comment]
It's fine. I just didn't see the update due to this.

**Comment by jborg** [comment]
I found a slightly prettier way to parse timestamps. So I pushed a fix for this. Thanks for the report

**Pull request closed without merging**
