### PR TITLE
implement --timestamp, iso8601-like utc timestamp string or reference file

### LINKED ISSUE #263: Specify the date and time of the backup
This might seem a little odd, but is very useful when migrating backup sets from other software. For instance, I recently converted a huge set of tgz files to Bup, and specified the date and time for each, thereby recreating the backup history. It doesn't have much use outside of this scenario, but would allow migrated sets to play nicely with the `attic prune` command. I imagine it's also a fairly simple addition.

***Comparison note****: Bup and Obnam both allow this.*

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
note: this needs bug #282 to be fixed first, because it will create timestamps with microseconds==0.

Without the #282 bug fix, one can work around by always giving a non-zero fraction of a second in the timestamps, e.g. 2015-04-19T16:14:15.1Z.

fixes #263.

### CODE REVIEW

**Comment by camh-** [comment]
Hmm, that's annoying that github puts each of my line comments as a separate pull request comment. It makes it rather noisy and loses the context of the comments. (If you can't tell, this is my first github code review as a reviewer).

**Comment by camh-** [comment]
I really feel it is wrong to force users to use UTC. datetimes should always be stored in UTC, but user interaction should default to their local time (with an option for UTC if the user desires).

Allowing only UTC timestamp strings shows up as in incongruity when listing the archives in a repository. The output of 'attic list <repo>' explicitly converts archive timestamps to local time (see helpers.py:format_archive() and helpers.py:to_localtime()).

I do not feel it is necessary to support arbitrary timezones (just localtime and UTC), and this can be achieved without external dependencies (such as pytz which is usually called in as soon as you need to deal with multiple timezones). Implementing an equivalent helper to to_localtime (from_localtime) could be done to support this.

**Comment by ThomasWaldmann** [comment]
@camh- thanks for the feedback, I'll see how I can improve it.

**Comment by ThomasWaldmann** [comment]
@camh- I agree with all what you said and improved the code.

BUT: tz support sucks. :| Thus, I did not add localtime or TZ support. I didn't want to require additional dependencies or complicate the code too much.

**Comment by camh-** [comment]
Generic TZ handling is painful (and requires something like pytz as an additional dependency), but local time support is not too hard. How about something like (untested in totality):

    def from_localtime(dt):
      seconds = time.mktime(dt.timetuple())
      return datetime.utcfromtimestamp(seconds).replace(microsecond=dt.microsecond)

And the body of the time string conversion:

    import itertools
    
    dates = ['%Y-%m-%d', '%Y-%j']
    times = ['T%H:%M:%S.%f', 'T%H:%M:%S', 'T%H:%M', 'T%H', '']
    zones = ['', 'Z']
    for format in itertools.product(dates, times, zones):
      try:
        dt = datetime.strptime(s, ''.join(format))
        return dt if format[2] == 'Z' else from_localtime(dt)
      except ValueError:
        pass

**Comment by jborg** [comment]
> Generic TZ handling is painful (and requires something like pytz as an additional dependency), but local time support is not too hard. How about something like (untested in totality):

Agreed, to_localtime uses a similar trick.

**Comment by ThomasWaldmann** [comment]
@camh- nice trick with the product. I'll work on integrating that and localtime support. BTW, I kept the "T" separate in case someone wants rather a space than a T, but that can be done in the same way.

**Comment by ThomasWaldmann** [comment]
OK, updated.

While doing that, found a slight issue with to_localtime - it does not support fractions of a second.
Chose to do the same with from_localtime and in general not to support fractions of a second with --timestamp (likely noone needs that anyway).

**Comment by ThomasWaldmann** [comment]
closing this pull request, seems unwanted.

**Pull request closed without merging**
