### PR TITLE
implement attic rename repo::oldname newname

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
I extracted the inner part of Archive.load into a new _load_meta method
that does not modify self and does not decode, so I could simply reuse it.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
closing this pull request, seems unwanted.

**Comment by fewyun** [comment]
Darn. I just dropped by looking for this feature again.

**Comment by ThomasWaldmann** [comment]
@fewyun have a look at borgbackup.

**Comment by fewyun** [comment]
Thanks! Attic will have to do for now because I have to complete some system updates first. I'll look into borgbackup.

**Pull request closed without merging**
